language: csharp
script:
  - nuget restore SourceDemoParser.Net.sln
  - msbuild /p:Configuration=Release SourceDemoParser.Net.sln
  - mono SourceDemoParser-CLI/bin/Release/SourceDemoParser-CLI.exe "messages=3;packets=3;commands=3;time;ticks;adj2;time;ticks" "Test/lasercrusher1338.dem"