language: csharp
mono: none
dotnet: 2.2
dist: xenial
script:
  - dotnet restore src/
  - dotnet build src/ -c Release
# Test
  - dotnet restore test/
  - dotnet build test/ -c PARSE_T
  - dotnet run -p test/ -c PARSE_T --no-build
# CLI Test
  - dotnet restore cli/
  - dotnet build cli/ -c Release
  - dotnet run -p cli/ -c Release --no-build -- demos/public/portal2_sp.dem -o ticks adj ticks
