language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: SourceDemoParser.Net.sln
script:
  - dotnet restore
  - dotnet build src/SourceDemoParser.Net/ -c Release -f netstandard1.4
# Test
  - dotnet build src/SourceDemoParser.Net.Test/ -c Release /p:DefineConstants="OE" -f netcoreapp1.1
  - dotnet run -p src/SourceDemoParser.Net.Test/ -c Release -f netcoreapp1.1
# CLI Test
  - dotnet build src/SourceDemoParser-CLI/ -c Release -f netcoreapp1.1
  - dotnet run -p src/SourceDemoParser-CLI/ -c Release -f netcoreapp1.1 "messages=3;packets=3;commands=3;time;ticks;adj2;time;ticks" "../../demos/portal2_coop.dem"